### ISSUE TITLE
Tutorial 3.5 in analisys_x.py

### ISSUE THREAD

**Issue by hejardon** [westpa/westpa2_tutorials#23]
Hello,
I'm following the tutorial 3.5 and found a bug in line 11 on the analysis_x.py script. Code:

w= w_ipa.WIPI()
"#At startup, it will load or run the analysis schemes specified in the configuration file (typically west.cfg)"
w.main()

It seems that object _w_ has no _main_ attribute, instead it has : _w.bin_labels, w.current, w.future, w.interation_, among others.  So, what is the purpose of _w.main()_ in this script?

thanks in advance,
Ed

**Comment by jeremyleung521** [comment]
Hi Ed, 

`WIPI()` is a subclass of `WESTParallelTool()` and its associated `main()` method essentially starts up a work manager for `w_ipa`. (https://github.com/westpa/westpa/blob/westpa2/src/westpa/tools/core.py#L166-L173)

Was there a specific error you're getting from this? If so, it would be great if you could post a traceback.

Best,

Jeremy L.

**Comment by hejardon** [comment]
Thanks for the reply...
by now Im working on the tutorial3.1 base_nacl with namd. In the runseg.sh
the are two variables not defined:

$WEST_PCOORD_RETURN
$WEST_COORD_RETURN

They seem to be environment variables, but when I ask for their value in
the shell, they throw a blank line. I could see that the python scripts
work, but they don't save distances nor coordinates due to the lack of
names for these files.

Also in line:
awk '{print $6, $7, $8}' > $WEST_COORD_RETURN

$6 $7 and $8 are the atom number, x and y coord... but z-coord is in  field
$9.  I think this awk code is not correct.

One last thing, in the last clean up command. the structure.psf is deleted,
but the calculatedistance.py script requires the psf to load the trajectory
seg.dcd, so it crashes when running the MDAnalyse for the distance
calculation.

any help would be appreciated to find where  $WEST_PCOORD_RETURN and
$WEST_COORD_RETURN
are defined

best,
Ed

**Comment by jeremyleung521** [comment]
Hi Ed,

A) Thank you for pointing out the mistake in the coordinate return. We've fixed it so it returns `$7, $8, $9` instead.

B) `calculatedistance.py` is run in [this line](https://github.com/westpa/westpa_tutorials/blob/main/additional_tutorials/basic_nacl_namd/westpa_scripts/runseg.sh#L78), which is before the cleanup in Lines 90-92. I haven't had any problems test-running a few iterations of this simulation. Would you be able to post the error messages? I'm sure it'll be captured in `seg_logs` folder.

C) `$WEST_PCOORD_RETURN` is created by default by WESTPA (necessary to run WE). `$WEST_COORD_RETURN` is generated based on information in [west.cfg](https://github.com/westpa/westpa_tutorials/blob/main/additional_tutorials/basic_nacl_namd/west.cfg#L44-L47) using the lines [here](https://github.com/westpa/westpa/blob/westpa2/src/westpa/core/propagators/executable.py#L217) (and other intricacies in WESTPA). These variables are only activated by the workers processes, so you'll have to put print statements in the `runseg.sh` (or similar) to get where the location is. They are paths to temp folders which are deleted afterwards.

Hope that helps.

-- JL

**Comment by hejardon** [comment]
Thanks!
I'll check it out...

**Comment by hejardon** [comment]
OK,
here the error msg i got (see the attached screenshot).

then I find that /tmp/tmp6wlhqw83 file got the distances:
58.570
59.125
58.491
59.124
...
which are calculated right.

**Comment by jeremyleung521** [comment]
> OK, here the error msg i got (see the attached screenshot). then I find that /tmp/tmp6wlhqw83 file got the distances: 58.570 59.125 58.491 59.124 ... which are calculated right. El vie, 27 ene 2023 a las 12:11, Eduardo Jardón ***@***.***>) escribió:
> […](#)
> Thanks! I'll check it out...>

The error message screenshot doesn't seem to be showing, but if the distance calculations are correct (which should also be in the west.h5) then there isn't a problem. Closing for now. Open a new issue ticket in [@westpa/westpa_tutorials](https://github.com/westpa/westpa_tutorials) or email the mailing list if you have any more questions. Happy to help!
