### ISSUE TITLE
bin section behaviour depends on number of bstates

### ISSUE THREAD

**Issue by rcrehuet** [westpa/westpa2_tutorials#25]
Hi,
I am comparing the `west.cfg` from tutorials 7.1 and 7.5. I wanted to use a RectilinearBinMapper for 7.5 so I copied the bins configuration section from 7.1. The result is:
```
      bins:
        type: RecursiveBinMapper
        base:
          type: RectilinearBinMapper
        # The edges of the bins 
          boundaries: 
          -  [ 0.00, 2.60, 2.80, 3.00, 3.20, 3.40, 3.60, 3.80,
               4.00, 4.50, 5.00, 5.50, 6.00, 7.00, 8.0, 9.0, 10.0,
               11.0, 12.0, 13.0, 14.0, 15.0, 'inf']
```
This raises an error in w_init:
```
  File "/home/ramon/miniconda3/envs/westpa-2.0/lib/python3.9/site-packages/westpa/core/_rc.py", line 62, in bins_from_yaml_dict
    mapper_configs = kwargs.pop('mappers')
KeyError: 'mappers'
```
I have submitted an issue because this error disappears if one starts from a single bstate (as 7.1 does). I think using the same bin mapper settings should not raise an error depending on whether a single bstate or multiple bstates are used.

**Comment by jeremyleung521** [comment]
Double checked with the west.cfg files Ramon provided and I was able to reproduce that it was an indentation problem that is causing the error/no error cases. Not a specific problem with our tutorial files, so closing!

Email chain with more information:
https://groups.google.com/g/westpa-users/c/tV-ChX2uSCs/m/t_1jCg1DBwAJ

**Comment by rcrehuet** [comment]
You are right Jeremy. What a silly mistake! My apolgies.
